### ISSUE TITLE
Attempting to create account leads to Internal Server Error

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/NoteApp-Issue-Tracker#1]
**Description**
Attempting to create an account instead leads to an error screen, preventing you from creating an account. This issue completely renders the app unusable, as you need to log in to access notes and account settings.

**URL**
https://asgn-noteapp.eltontay.com/create

**How to reproduce:**
Proceed to login page, click the link at the bottom to create an account.
Fill in email and password details as shown:
![image](https://user-images.githubusercontent.com/34486197/180500969-1ae7a7fa-f614-41f2-b99f-1bd957c7eff8.png)
Clicking the button [Register] sends you to a 500 Internal Server Error screen.
![image](https://user-images.githubusercontent.com/34486197/180501027-9d0b8224-501b-4d1e-8fb0-60a16e659c4f.png)

**Desktop details:**
 - OS: Windows 10 Home
 - Browser: Google Chrome
 - Version: Windows 10 Build 19044, Chrome 103.0.5060.114

**Comment by IngeniousCoder** [comment]
patched, this issue shall still count
