### ISSUE TITLE
Reset password feature ignores if account even exists

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/NoteApp-Issue-Tracker#2]
**Description**
When entering an email address that is not associated with an account into the Forget Password screen, it still shows the notification that a link has been sent to reset password. Checking the email inbox reveals no email with a link has been sent.

**URL**
https://asgn-noteapp.eltontay.com/reset

**How to Reproduce**
Proceed to login page, click link on bottom to reset password.
Enter an email address not associated with any account.

The website says a link has been sent to reset the password of that account, despite the account not existing.
![image](https://user-images.githubusercontent.com/34486197/180502442-e4307e2e-c524-4d85-a7fa-ccf3fe7cc3a1.png)

Desktop details:

- OS: Windows 10 Home
- Browser: Google Chrome
- Version: Windows 10 Build 19044, Chrome 103.0.5060.114

**Comment by IngeniousCoder** [comment]
Invalid; This is a typical security measure for Excessive Data Exposure, we dont want to let attackers verify if an account exists or not.
