### ISSUE TITLE
2FA QR Code on new accounts not supported by authenticator applications

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/NoteApp-Issue-Tracker#3]
**Description**
On a new account, when attempting to scan the 2FA QR Code for authenticator app, the application throws a QR Code not supported error.

**URL**
https://asgn-noteapp.eltontay.com/account/edit

**How to reproduce**
Create a new account
Proceed to account tab, click Edit Account
Scan QR code with an authenticator app (Twilio Authy used here)
![image](https://user-images.githubusercontent.com/34486197/180504780-8ee0f634-5a28-4296-9ed6-75859a0a4265.png)
Authenticator app fails to recognise QR code.

**Desktop details:**

- OS: Windows 10 Home
- Browser: Google Chrome
- Version: Windows 10 Build 19044, Chrome 103.0.5060.114

**Comment by IngeniousCoder** [comment]
patched
