### ISSUE TITLE
Search button is useless

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/NoteApp-Issue-Tracker#4]
**Description**
Attempting to click the search icon in the top right simply redirects the user to the same page.

**URL**
Bug is present in all areas of the app.

**How to reproduce**
Click the search icon (magnifying glass) in the top right on any page of the app.

**Desktop details:**

- OS: Windows 10 Home
- Browser: Google Chrome
- Version: Windows 10 Build 19044, Chrome 103.0.5060.114
-

**Comment by IngeniousCoder** [comment]
sent button to space
