### ISSUE TITLE
Note technically has no option to set title, and cannot delete created notes.

### ISSUE THREAD

**Issue by Zbok0** [IngeniousCoder/NoteApp-Issue-Tracker#5]
https://asgn-noteapp.eltontay.com/notes/

Has no title, cause title is essentially the content in the note. Not delete option for notes created.

**Comment by IngeniousCoder** [comment]
Added 
```<p> Line 1 of your note is automatically set as the title.</p>```
within line 1 of noteeditor.

decided not to do remove note because lazy + its my functionality anyways so it affects me, not causing any of yall individual results to drop anyway
