### ISSUE TITLE
Account page has no option to remove or add card.

### ISSUE THREAD

**Issue by Zbok0** [IngeniousCoder/NoteApp-Issue-Tracker#6]
https://asgn-noteapp.eltontay.com/account/

Should there be a option to add and remove also ?

**Comment by IngeniousCoder** [comment]
add is within edit account

Remove will add for Wk17

**Comment by IngeniousCoder** [comment]
decided not to allow and enforce at least one card if you put;

rationale : if we are charging u and u remove, then we can no longer charge u
this implementation has been seen before at places like ovh, which refuse to let u remove all cards and mandate at least 1 card at any time
