### ISSUE TITLE
No examples on credit card details entering. And shouldn't be telling people what encryption website use.

### ISSUE THREAD

**Issue by Zbok0** [IngeniousCoder/NoteApp-Issue-Tracker#7]
Commonly websites when entering credit card details should give examples to guide user.

Also website usually don't tell them what encryption they are using for the credit card details

**Comment by IngeniousCoder** [comment]
https://telegram.org/faq#q-so-how-do-you-encrypt-data

There is no reason not to reveal encryption method; so long as we do not reveal the IV and Keys
