### ISSUE TITLE
Note Title can add button using <input> in /notes/editor

### ISSUE THREAD

**Issue by LoofyDoofy** [IngeniousCoder/NoteApp-Issue-Tracker#9]
<a href="https://youtube.com"><input type="button" value="Test" href="https://youtube.com"></a> using this can make a button at the /notes page

**Comment by IngeniousCoder** [comment]
so what is the exact payload you threw that made it run js??

**Comment by LoofyDoofy** [comment]
its not a script but i wrote
<a href="https://youtube.com"><input type="button" value="Test" href="https://youtube.com"></a>

**Comment by IngeniousCoder** [comment]
verified invalid
